baseURL = "http://example.org/"
languageCode = "en-us"
theme = "sada"
disableKinds = ["taxonomy", "taxonomyTerm"]

# for github pages
publishDir = "docs"
canonifyurls = true

[params]
    name = "ntatsuya homepage"
    title = "ntatsuya homepage"
    author = "Tatsuya Nishiyama"
    description = "Self-introduction"
    copyright = "Custom copyright message"
    theme = "dark" # `dark` or `light`
    useResources = false

    # Profile section
    [params.profile]
        name = "Tatsuya Nishiyama"
        photo = "images/tatsuya.JPG"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
        icon = "fab fa-twitter"
        url = "https://twitter.com/yama_nisshii"
        title = "Twitter"

        [[params.social.list]]
        icon = "fab fa-github"
        url = "https://github.com/ntatsuyag"
        title = "GitHub"
		
		[[params.social.list]]
        icon = "fas fa-edit"
        url = "https://qiita.com/ntatsuya"
        title = "Qiita"
		
		[[params.social.list]]
        icon = "fas fa-envelope"
        url = "mailto:nityamanishi@gmail.com"
        title = "Mail"		

    # Education section
    [params.education]
        title = "Education"

        [[params.education.list]]
        degree = "Masters's Degree"
        college = "Nagoya Institute of Technology"
        dates = "2020 - Present"

        [[params.education.list]]
        degree = "Bachelor's Degree"
        college = "Nagoya Institute of Technology"
        dates = "2016 - 2020"

    # Languages section
    [params.language]
        title = "Languages"

        [[params.language.list]]
        language = "japanese"
        level = "Fluent"
				
        [[params.language.list]]
        language = "English"
        level = "Basic"

    # Interests section
    [params.hobbies]
        title = "Hobbies"

        [[params.hobbies.list]]
        interest = "Break dance"

    [params.aboutme]
        description = "I'm 2nd grade Master's student at Nagoya Institute of Technology. My main areas of interest are Dialog system, Deep Learning, Machine learning, Neural language processing. I'm into investing in crypto currency. If you want to contact me, you send email to *nityamanishi@gmail.com*."

    # Experiences section
    [params.experiences]
        title = "Experiences"

        [[params.jobs.list]]
        position = "Intern"
        dates = "2020/9"
		link = "https://www.ai-shift.co.jp/techblog/1293"
        company = "AI Shift"

    # Projects section
    [params.projects]
        title = "Projects"

        [[params.projects.list]]
        title = "The Eighth Dialog System Technology Challenge (DSTC8)"
        url = "https://sites.google.com/dstc.community/dstc8/aaai-20-workshop#h.p_S6XuCFAUkhQo"
        description = "*Speaker-Aware BERT for Multi-Party Dialog Response Selection*, Tatsuya Nishiyama, Ryota Tanaka, Yuya Ishijima, Akinobu Lee"
		
    # Skills section
    [params.skills]
        title = "Skills"

        [[params.skills.list]]
        skill = "Python"
        skillrating = 70 # out of 100
                
        [[params.skills.list]]
        skill = "C, Java"
        skillrating = 40
		
        [[params.skills.list]]
        skill = "HTML/CSS"
        skillrating = 15

        [[params.skills.list]]
        skill = "Git, Docker"
        skillrating = 50